server {
    listen 80;
    server_name localhost;

    # Racine des fichiers de l'application Angular
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redirige toutes les requêtes de routage vers index.html pour Angular
        try_files $uri $uri/ /index.html;
    }

    # Optionnel : Si votre Front doit attaquer la Gateway Docker directement via Nginx
    # location /api/ {
    #     proxy_pass http://gateway-service:8181/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }

    # Gestion des pages d'erreur Nginx
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}